// Browser-side ONNX session loader for the U-Net+ConvLSTM fire-spread model.
//
// Lazy singleton: the worker is created on first call to `runFireSpread`.
// If `/fire-spread-smoke.onnx` is missing we fail fast with a friendly error
// — the caller is expected to fall back to the CA-only path.

const MODEL_URL = "/fire-spread-smoke.onnx";

export interface FireSpreadResult {
  /** Sigmoid burn probability raster, t+1h horizon. Length H*W. */
  p1h: Float32Array;
  /** Sigmoid burn probability raster, t+6h horizon. Length H*W. */
  p6h: Float32Array;
  /** Sigmoid burn probability raster, t+24h horizon. Length H*W. */
  p24h: Float32Array;
  /** [H, W] of every probability raster. */
  dims: [number, number];
}

export interface FireSpreadInputShape {
  readonly 0: 1;
  readonly 1: 4;
  readonly 2: 14;
  readonly 3: number;
  readonly 4: number;
  readonly length: 5;
}

interface PendingRequest {
  resolve: (result: FireSpreadResult) => void;
  reject: (error: Error) => void;
}

interface WorkerHandle {
  worker: Worker;
  ready: Promise<void>;
}

let workerHandle: WorkerHandle | null = null;
let nextRequestId = 1;
const pending = new Map<number, PendingRequest>();

async function probeModelAvailable(): Promise<boolean> {
  try {
    const head = await fetch(MODEL_URL, { method: "HEAD", cache: "no-store" });
    return head.ok;
  } catch {
    return false;
  }
}

function createWorker(): WorkerHandle {
  // `import.meta.url` gives Webpack/Turbopack/Vite a module-graph hook to
  // bundle the worker entry on its own chunk. Keeping the worker file
  // co-located with the loader so the build tool always finds it.
  const worker = new Worker(new URL("./fire-spread-onnx.worker.ts", import.meta.url), {
    type: "module",
  });

  worker.addEventListener("message", (event: MessageEvent<Record<string, unknown>>) => {
    const data = event.data;
    if (!data || typeof data !== "object") return;
    const id = typeof data.id === "number" ? data.id : -1;
    const type = data.type;

    if (type === "ready") {
      // Init resolves separately via the readiness promise stored below.
      return;
    }

    const handler = pending.get(id);
    if (!handler) return;
    pending.delete(id);
    if (type === "result") {
      handler.resolve({
        p1h: data.p1h as Float32Array,
        p6h: data.p6h as Float32Array,
        p24h: data.p24h as Float32Array,
        dims: data.dims as [number, number],
      });
    } else if (type === "error") {
      handler.reject(new Error(typeof data.message === "string" ? data.message : "ONNX error"));
    }
  });

  // Onerror only fires for top-level worker bootstrap problems; we still
  // bubble it back to anyone awaiting `runFireSpread`.
  worker.addEventListener("error", (event) => {
    const error = new Error(`ONNX worker error: ${event.message}`);
    pending.forEach((p) => p.reject(error));
    pending.clear();
  });

  const ready = new Promise<void>((resolve, reject) => {
    const initId = nextRequestId++;
    const onMessage = (event: MessageEvent<Record<string, unknown>>) => {
      const data = event.data;
      if (data && data.type === "ready" && data.id === initId) {
        worker.removeEventListener("message", onMessage);
        resolve();
      } else if (data && data.type === "error" && data.id === initId) {
        worker.removeEventListener("message", onMessage);
        reject(new Error(typeof data.message === "string" ? data.message : "ONNX init error"));
      }
    };
    worker.addEventListener("message", onMessage);
    worker.postMessage({ type: "init", id: initId, modelUrl: MODEL_URL });
  });

  return { worker, ready };
}

/**
 * Run the U-Net+ConvLSTM fire-spread model in a Web Worker.
 *
 * @param input - Flat Float32Array, length 1 * 4 * 14 * H * W.
 * @param shape - [1, 4, 14, H, W]. Caller must keep H == W in practice
 *                because the bundled smoke model was exported at 32x32 — the
 *                ConvLSTM only emits a clean output if the spatial shape is
 *                divisible by 16.
 * @returns p1h / p6h / p24h burn-probability rasters, plus their dims.
 */
export async function runFireSpread(
  input: Float32Array,
  shape: [1, 4, 14, number, number],
): Promise<FireSpreadResult> {
  // Probe the model first so a missing-file path produces the friendly
  // fallback error in BOTH browser and (mocked) test environments.
  if (!workerHandle) {
    const available = await probeModelAvailable();
    if (!available) {
      // Friendly degradation: the caller is expected to fall back to the CA.
      // We deliberately do NOT throw a hard build-time error here — the
      // model file is ~90 KB but is only generated by ml/training/train.py,
      // which not every checkout has run.
      // eslint-disable-next-line no-console
      console.warn(
        `[fire-spread-onnx] ${MODEL_URL} is missing — falling back to CA-only fire spread.`,
      );
      throw new Error(
        `ONNX model not found at ${MODEL_URL}; run \`pnpm --filter ml export-onnx\` to generate it.`,
      );
    }
    if (typeof window === "undefined" || typeof Worker === "undefined") {
      throw new Error("runFireSpread can only be called in a browser environment");
    }
    workerHandle = createWorker();
  }

  await workerHandle.ready;

  const id = nextRequestId++;
  return new Promise<FireSpreadResult>((resolve, reject) => {
    pending.set(id, { resolve, reject });
    // Transfer the underlying buffer so we don't pay the structured-clone
    // cost on every frame. The caller is expected to discard `input` after.
    workerHandle!.worker.postMessage(
      {
        type: "infer",
        id,
        data: input,
        shape: Array.from(shape),
      },
      [input.buffer],
    );
  });
}

/**
 * Tear down the singleton. Useful in tests + on hot module reload.
 */
export function disposeFireSpreadSession(): void {
  if (workerHandle) {
    workerHandle.worker.terminate();
    workerHandle = null;
  }
  pending.forEach((p) =>
    p.reject(new Error("fire-spread session disposed before request completed")),
  );
  pending.clear();
}

/** Test hook: peek at whether the singleton is initialized. */
export function __isSessionInitializedForTest(): boolean {
  return workerHandle !== null;
}
